# This rule is not used by the project fanet-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over fanet.restart.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fanet-operator
    app.kubernetes.io/managed-by: kustomize
  name: drone-admin-role
rules:
- apiGroups:
  - fanet.restart.io
  resources:
  - drones
  verbs:
  - '*'
- apiGroups:
  - fanet.restart.io
  resources:
  - drones/status
  verbs:
  - get
