apiVersion: fanet.restart.io/v1alpha1
kind: Fanet
metadata:
  labels:
    app.kubernetes.io/name: fanet-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo-fanet
spec:
  # List of Drones in this FANET
  drones:
    - name: drone-rp3001
      nodeRef:
        name: worker-rp3001
    - name: drone-rp3002
      nodeRef:
        name: worker-rp3002
