## Append samples of your project ##
resources:
- fanet_v1alpha1_fanet.yaml
- fanet_v1alpha1_drone.yaml
- fanet_v1alpha1_servicechain.yaml
- fanet_v1alpha1_virtualfunction.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
