---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: fanets.fanet.restart.io
spec:
  group: fanet.restart.io
  names:
    kind: Fanet
    listKind: FanetList
    plural: fanets
    shortNames:
    - fn
    singular: fanet
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Total number of drones in the FANET
      jsonPath: .status.totalDroneCount
      name: TotalDrones
      type: integer
    - description: Number of drones in flight
      jsonPath: .status.inFlightCount
      name: InFlight
      type: integer
    - description: Number of drones leaving
      jsonPath: .status.leavingCount
      name: Leaving
      type: integer
    - description: Number of drones not available
      jsonPath: .status.notAvailableCount
      name: NotAvailable
      type: integer
    - description: Total number of virtual functions in the FANET
      jsonPath: .status.vfTotal
      name: VFTotal
      type: integer
    - description: Age of the FANET
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Fanet is the Schema for the fanets API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: FanetSpec defines the desired state of Fanet.
            properties:
              drones:
                description: Drones is the list of drones in this FANET
                items:
                  description: DroneReference contains reference to a Drone
                  properties:
                    name:
                      description: NodeRef is the reference to the node the drone
                        is hosting
                      type: string
                    nodeRef:
                      description: DroneName is the name of the drone
                      properties:
                        name:
                          type: string
                      required:
                      - name
                      type: object
                  required:
                  - name
                  type: object
                type: array
            type: object
          status:
            description: FanetStatus defines the observed state of Fanet.
            properties:
              droneStatuses:
                description: DroneStatuses is the status of each drone
                items:
                  description: DroneStatusInfo contains status information about a
                    drone
                  properties:
                    batteryLevel:
                      type: integer
                    computingDrone:
                      type: boolean
                    cpuAvailable:
                      type: string
                    droneName:
                      type: string
                    memoryAvailable:
                      type: string
                    nodeReady:
                      type: boolean
                    operationalStatus:
                      description: |-
                        OperationalStatus describes the operational status of the drone.
                        Only one of the following statuses can be set at a time.
                        If none of the following statuses is set, the status is considered unknown.
                      enum:
                      - Flying
                      - Leaving
                      - NotAvailable
                      type: string
                    vfCount:
                      type: integer
                  required:
                  - droneName
                  type: object
                type: array
              inFlightCount:
                description: InFlightCount is the number of drones in flight
                type: integer
              leavingCount:
                description: LeavingCount is the number of drones leaving
                type: integer
              notAvailableCount:
                description: NotAvailableCount is the number of drones not available
                type: integer
              totalDroneCount:
                description: TotalDroneCount is the total number of drones
                type: integer
              vfTotal:
                description: VFTotal is the total number of virtual functions
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
